name: coverage

on: [push, pull_request]

jobs:
  codacy-coverage-reporter:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install compiler
        run: |
            sudo apt-get update
            sudo apt-get install g++-11 -y

      - name: Compile tests
        env:
          CXXFLAGS: "--coverage -fno-inline"
          CXX: g++-11
        run: |
          cmake -DSIMPLE_UTILITY_BUILD_TESTS=ON -B out -S .
          cmake --build out -j4

      - name: Run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest --test-dir out/tests --timeout 30 -C Debug -j4

      - name: Collect data
        run: |
          sudo apt install lcov
          lcov -c -d out/tests -o coverage.info
          lcov -l coverage.info

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN  }}
          coverage-reports: coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          project-token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          name: Simple-Utility
          fail_ci_if_error: true
          verbose: true
