name: publish docs

env:
    BUILD_DIR: ./build
    CMAKE_ADDITIONAL_CONFIG_ARGS: -DSIMPLE_UTILITY_GEN_DOCS_ENABLED=ON

on: [push]
#  release:
#    types: [released]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: pommalabs/doxygen:latest #greenbone/doxygen:latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate Docs
      run: |
        cmake  --log-level=VERBOSE -B ${{ env.BUILD_DIR }} -S . ${{ env.CMAKE_ADDITIONAL_CONFIG_ARGS }}
        cmake --build ${{ env.BUILD_DIR }} --target GenerateDocs

#    - name: Publish Docs
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ${{ env.BUILD_DIR }}/docs/html
