name: publish docs

env:
    WORKING_DIR: ./docs
    DOXYFILE: Doxyfile
    BUILD_DIR: ./docs/build
    CONFIGURE_DOXY_FLAG: Simple-Utility_CONFIGURE_DOXYGEN

on:
  release:
    types: [released]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure Doxygen
      run: |
        cmake -D${{ env.CONFIGURE_DOXY_FLAG }}=ON

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: ${{ env.WORKING_DIR }}
        doxyfile-path: ${{ env.DOXYFILE }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.BUILD_DIR }}/html
