name: publish docs

on:
  release:
    types: [released]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.3.1

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/docs/html
