name: run tests

env:
  BUILD_DIR: out    # root build directory
  TEST_DIR: tests   # relative directory below BUILD_DIR
  CMAKE_OPTIONS: -DSimple-Utility_BUILD_TESTS=ON

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [master, development]
  pull_request:
    branches: [development]

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - pkg: g++-11
            exe: g++-11
          - pkg: g++-10
            exe: g++-10
          - pkg: clang-13
            exe: clang++-13
          - pkg: clang-12
            exe: clang++-12
          - pkg: clang-11
            exe: clang++-11
          - pkg: clang-10
            exe: clang++-10
            
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: |
        sudo apt-get update
        sudo apt-get install ${{ matrix.compiler.pkg }} -y
    - name: Compile tests
      env:
        CXX: ${{ matrix.compiler.exe }}
      run: |
        cmake ${{ env.CMAKE_OPTIONS }} -B ${{ env.BUILD_DIR }} -S .
        cmake --build ${{ env.BUILD_DIR }} -j4
    - name: Run tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --test-dir ${{ env.BUILD_DIR }}/${{ env.TEST_DIR }} --timeout 30 -C Debug -j4

  windows:
    runs-on: windows-2022
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        toolset: [v142, v143, clang-cl]
        include:
          - toolset: v142
            toolset_option: -T"v142"
          - toolset: v143
            toolset_option: -T"v143"
          - toolset: clang-cl
            toolset_option: -T"ClangCl"

    steps:
    - uses: actions/checkout@v2
    - name: Compile tests
      run: |
        cmake ${{ env.CMAKE_OPTIONS }} ${{ matrix.toolset_option }} -B ${{ env.BUILD_DIR }} -S .
        cmake --build ${{ env.BUILD_DIR }} -j4
    - name: Run tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --test-dir ${{ env.BUILD_DIR }}/${{ env.TEST_DIR }} --timeout 30 -C Debug -j4

#  macos:
#    runs-on: macos-latest
#    timeout-minutes: 10
#    
#    strategy:
#      fail-fast: false
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Compile tests
#      run: |
#        cmake ${{ env.CMAKE_OPTIONS }} -B ${{ env.BUILD_DIR }} -S .
#        cmake --build ${{ env.BUILD_DIR }} -j4
#    - name: Run tests
#      env:
#        CTEST_OUTPUT_ON_FAILURE: 1
#      run: ctest --test-dir ${{ env.BUILD_DIR }}/${{ env.TEST_DIR }} --timeout 30 -C Debug -j4
